accounts/urls.py
from django.urls import path
from django.urls import include
from .views import *

urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('signup/', SignUp.as_view(), name='signup'),
	path('logout/', LogOut, name='logout'),
]

cwproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('veterinary.urls')),
    path('personal/', include('personal.urls')),
    path('comments/', include('comments_app.urls')),
]


from django.conf.urls.static import static
from django.conf import settings
if  settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path
from django.urls import include

from .views import *

urlpatterns = [
    path('', Personal.as_view(), name='personal'),
    path('change/', ChangeClient.as_view(), name='change'),
    path('add/', AddAnimal.as_view(), name='add_animal'),
    path('pet/<int:id>/', GetAnimal.as_view(), name='get_animal'),
    path('pet/<int:id>/change/', ChangeAnimal.as_view(), name='change_animal'),
    path('pet/<int:id>/delete/', DeleteAnimal.as_view(), name='delete_animal'),
    path('changestaff/', ChangeStaff.as_view(), name='change_staff'),
    path('ajax/load-breeds/', load_breeds, name='ajax_load_breeds'),
]

personal/models.py
from django.db import models

from accounts.models import User
# Create your models here.

class StaffModel(models.Model):
	education = models.CharField(max_length=1024)
	qualification = models.CharField(max_length=512)
	description = models.CharField(max_length=2048)
	points = models.PositiveSmallIntegerField(default=0)
	user = models.OneToOneField(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.user.first_name+' '+self.user.last_name+' '+self.user.middle_name

class DistrictModel(models.Model):
	name = models.CharField(max_length=512)

	def __str__(self):
		return self.name

class ClientModel(models.Model):
	district = models.ForeignKey(DistrictModel, on_delete=models.CASCADE)
	user = models.OneToOneField(User, on_delete = models.CASCADE)


class AnimalModel(models.Model):
	name = models.CharField(max_length=256)

	def __str__(self):
		return self.name

class BreedModel(models.Model):
	name = models.CharField(max_length=256)
	animal = models.ForeignKey(AnimalModel, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class AnimaClientModel(models.Model):
	nickname = models.CharField(max_length=256, blank=True)
	age = models.PositiveSmallIntegerField(default=0, blank=True)
	foto = models.ImageField(null=True, blank=True)
	animal = models.ForeignKey(AnimalModel, on_delete=models.CASCADE)
	client = models.ForeignKey(ClientModel, on_delete=models.CASCADE)
	breed = models.ForeignKey(BreedModel, on_delete=models.CASCADE)

	def __str__(self):
		return self.nickname

personal/forms.py
from django import forms

from .models import *

class AddAnimalForm(forms.ModelForm):

	nickname = forms.CharField(label='Кличка', max_length=256, required=False)
	animal = forms.ModelChoiceField(label='Выберите животное', queryset=AnimalModel.objects.all())
	breed = forms.ModelChoiceField(label='Выберите породу', queryset=BreedModel.objects.all())
	age = forms.IntegerField(label='Кол-во полных лет')
	foto = forms.ImageField(label='Фото', required=False)

	class Meta:
		model = AnimaClientModel
		fields = ('nickname', 'animal', 'breed', 'age', 'foto')

	nickname.widget.attrs.update({'class':'form-control', 'placeholder':'Кличка'})
	animal.widget.attrs.update({'class':'form-control'})
	breed.widget.attrs.update({'class':'form-control'})
	age.widget.attrs.update({'class':'form-control', 'placeholder':'Кол-во полных лет'})

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		#self.fields['breed'].queryset = BreedModel.objects.none()
		if 'animal' in self.data:
			try:
				animal_id = int(self.data.get('animal'))
				self.fields['breed'].queryset = BreedModel.objects.filter(animal=animal_id).order_by('name')
			except (ValueError, TypeError):
				pass  
		elif self.instance.pk:
			self.fields['breed'].queryset = self.instance.animal.breed_set.order_by('name')

class ChangeClientForm(forms.Form):
	name = forms.CharField(label='Имя', max_length=256, required=False)
	surname = forms.CharField(label='Фамилия', max_length=256, required=False)
	middle = forms.CharField(label='Отчество', max_length=256, required=False)
	email = forms.EmailField(label='Почта', max_length=256, required=False)
	district = forms.ModelChoiceField(label='Район', queryset=DistrictModel.objects.all(), required=False)
	foto = forms.FileField(label='Фото',required=False)

	name.widget.attrs.update({'class':'form-control', 'placeholder':'Имя'})
	surname.widget.attrs.update({'class':'form-control', 'placeholder':'Фамилия'})
	middle.widget.attrs.update({'class':'form-control', 'placeholder':'Отчество'})
	email.widget.attrs.update({'class':'form-control', 'placeholder':'Почта'})
	district.widget.attrs.update({'class':'form-control', 'placeholder':'Район'})

class ChangeStaffForm(forms.Form):
	name = forms.CharField(label='Имя', max_length=256)
	surname = forms.CharField(label='Фамилия', max_length=256)
	middle = forms.CharField(label='Отчество', max_length=256)
	email = forms.EmailField(label='Почта', max_length=256)
	education = forms.CharField(label='Образование', max_length=1024)
	qualification = forms.CharField(label='Квалификация', max_length=512)
	description = forms.CharField(label='Описание', max_length=2048)
	foto = forms.FileField(label='Фото')

	name.widget.attrs.update({'class':'form-control', 'placeholder':'Имя'})
	surname.widget.attrs.update({'class':'form-control', 'placeholder':'Фамилия'})
	middle.widget.attrs.update({'class':'form-control', 'placeholder':'Отчество'})
	email.widget.attrs.update({'class':'form-control', 'placeholder':'Почта'})
	education.widget.attrs.update({'class':'form-control', 'placeholder':'Образование'})
	qualification.widget.attrs.update({'class':'form-control', 'placeholder':'Квалификация'})
	description.widget.attrs.update({'class':'form-control', 'placeholder':'Описание'})

personal/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import *
from .forms import *
# Create your views here.


class Personal(generic.View):

	@method_decorator(login_required())
	def get(self, request):
		animals = None
		if request.user.is_staff:
			try:
				pers = StaffModel.objects.get(user=request.user)
			except:
				pers = None
		else:
			try:
				pers = ClientModel.objects.get(user=request.user)
			except:
				pers = None
			if pers:
				try:
					animals = AnimaClientModel.objects.filter(client=pers)
				except:
					animals = None

		return render(request, 'personal/personal.html', context={'pers': pers, 'animals': animals})

#Client personal

def load_breeds(request):
	animal = request.GET.get('animal')
	breeds = BreedModel.objects.filter(animal=animal).order_by('name')
	return render(request, 'personal/city_dropdown_list_options.html', {'breeds': breeds})

class AddAnimal(generic.View):

	@method_decorator(login_required())
	def get(self, request):
		form = AddAnimalForm()
		return render(request, 'personal/addanimal.html', context={'form': form})

	@method_decorator(login_required())
	def post(self, request):
		form = AddAnimalForm(request.POST, request.FILES)
		if form.is_valid():
			nickname = form.cleaned_data['nickname']
			animal = form.cleaned_data['animal']
			breed = form.cleaned_data['breed']
			age = form.cleaned_data['age']
			try:
				foto = request.FILES['foto']
			except:
				foto = None
			client = ClientModel.objects.get(user=request.user)
			model = AnimaClientModel(nickname=nickname,age=age,
				foto=foto,animal=animal,client=client,
				breed=breed)
			model.save()
		return redirect('personal')

from django.contrib.auth.mixins import LoginRequiredMixin
class ChangeClient(LoginRequiredMixin, generic.View):

	@method_decorator(login_required())
	def get(self, request):
		client = ClientModel.objects.get(user=request.user)
		initial = {
			'name': request.user.first_name,
			'surname': request.user.last_name,
			'middle': request.user.middle_name,
			'email': request.user.email,
			'district': client.district,
			'foto':  request.user.foto,
		}
		form = ChangeClientForm(initial=initial)
		return render(request, 'personal/change.html', context={'form': form})

	@method_decorator(login_required())
	def post(self, request):
		form = ChangeClientForm(request.POST, request.FILES)
		if form.is_valid():
			name = form.cleaned_data['name']
			surname = form.cleaned_data['surname']
			middle = form.cleaned_data['middle']
			email = form.cleaned_data['email']
			district = form.cleaned_data['district']
			try:
				foto = request.FILES['foto']
			except:
				foto = None

			user_model = User.objects.get(id=request.user.id)
			user_model.first_name = name
			user_model.last_name = surname
			user_model.middle_name = middle
			user_model.email = email
			if foto:
				user_model.foto = foto
			user_model.save()
			client_model = ClientModel.objects.get(user=request.user)
			client_model.district = district
			client_model.save()
			return redirect('personal')
		return redirect('index')

#Pets personal


class GetAnimal(generic.View):

	@method_decorator(login_required())
	def get(self, request, id):
		animal = AnimaClientModel.objects.get(id=id)
		return render(request, 'personal/animal.html', context={'animal': animal})

class ChangeAnimal(generic.View):

	@method_decorator(login_required())
	def get(self, request, id):
		animal = AnimaClientModel.objects.get(id=id)
		initial = {
			'nickname': animal.nickname,
			'animal': animal.animal,
			'breed': animal.breed,
			'age': animal.age,
			'foto': animal.foto,
		}
		form = AddAnimalForm(initial=initial)
		return render(request, 'personal/changeanimal.html', context={'form': form, 'idan': id})

	@method_decorator(login_required())
	def post(self, request, id):
		form = AddAnimalForm(request.POST, request.FILES)
		if form.is_valid():
			nickname = form.cleaned_data['nickname']
			animal = form.cleaned_data['animal']
			breed = form.cleaned_data['breed']
			age = form.cleaned_data['age']
			try:
				foto = request.FILES['foto']
			except:
				foto = None
			animal_model = AnimaClientModel.objects.get(id=id)
			animal_model.nickname = nickname
			animal_model.animal = animal
			animal_model.breed = breed
			animal_model.age = age
			if foto:
				animal_model.foto = foto
			animal_model.save()
		return redirect('get_animal', id=id)

class DeleteAnimal(generic.View):

	@method_decorator(login_required())
	def get(self, request, id=None):
		try:
			animal = AnimaClientModel.objects.get(id=id)
		except:
			animal = None
		animal.delete()
		request.method = 'GET'
		return redirect('personal')	

#Doc personal

from django.contrib.auth.mixins import LoginRequiredMixin
class ChangeStaff(LoginRequiredMixin, generic.View):

	@method_decorator(login_required())
	def get(self, request):
		staff = StaffModel.objects.get(user=request.user)
		initial = {
			'name': request.user.first_name,
			'surname': request.user.last_name,
			'middle': request.user.middle_name,
			'email': request.user.email,
			'education': staff.education,
			'qualification': staff.qualification,
			'description': staff.description,
			'foto':  request.user.foto,
		}
		form = ChangeStaffForm(initial=initial)
		return render(request, 'personal/change_staff.html', context={'form': form})

	@method_decorator(login_required())
	def post(self, request):
		form = ChangeStaffForm(request.POST, request.FILES)
		if form.is_valid():
			name = form.cleaned_data['name']
			surname = form.cleaned_data['surname']
			middle = form.cleaned_data['middle']
			email = form.cleaned_data['email']
			education = form.cleaned_data['education']
			qualification = form.cleaned_data['qualification']
			description = form.cleaned_data['description']
			try:
				foto = request.FILES['foto']
			except:
				foto = None

			user_model = User.objects.get(id=request.user.id)
			user_model.first_name = name
			user_model.last_name = surname
			user_model.middle_name = middle
			user_model.email = email
			if foto:
				user_model.foto = foto
			user_model.save()
			staff_model = StaffModel.objects.get(user=request.user)
			staff_model.education = education
			staff_model.qualification = qualification
			staff_model.description = description
			staff_model.save()
			return redirect('personal')
		return redirect('index')

personal/templates/personal/addanimal.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block title %}
	Добавить питомца
{% endblock %}

{% block link %}


{% endblock %}

{% block content_title %}
	<p class="m">Добавить питомца</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <a href="{% url 'personal' %}">Личный кабинет</a> / <span>Добавить питомца</span></p>
{% endblock %}

{% block content %}
	<div class="col-md-8 offset-md-2">
		<form method="POST" id="personForm" action="{% url 'add_animal' %}" enctype="multipart/form-data" data-breeds-url="{% url 'ajax_load_breeds' %}">
			{% csrf_token %}

			{% for item in form %}
			<div class="forms">
				<p class="forms-name">{{ item.label }}</p>
				{{ item }}
			</div>
			{% endfor %}

			<button class='forms-btn btn btn-secondary' type='submit'>Добавить</button>
		</form>

		{# Assumes you setup the password_reset view in your URLconf #}
		<!-- <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p> -->
	</div>
	
  <script>

	$("#id_animal").change(function () {
	  var url = $("#personForm").attr("data-breeds-url");  // get the url of the `load_cities` view
	  var animalId = $(this).val();  // get the selected country ID from the HTML input

	  $.ajax({                       // initialize an AJAX request
	    url: '{% url 'ajax_load_breeds' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
	    data: {
	      'animal': animalId      // add the country id to the GET parameters
	    },
	    success: function (data) {   // `data` is the return of the `load_cities` view function
	      $("#id_breed").html(data);  // replace the contents of the city input with the data that came from the server
	    }
	  });

	});
  </script>
{% endblock %}

personal/templates/personal/animal.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}



{% block title %}
	Страничка питомца
{% endblock %}

{% block content_title %}
	<p class="m">Страничка питомца</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <a href="{% url 'personal' %}">Личный кабинет</a> / <span>Страничка питомца</span></p>
{% endblock %}

{% block content %}
	<div class="row docdetail">
		<div class="col-md-3 d-flex justify-content-center align-items-center">
			{% if animal.foto %}
				<img class="img-fluid  rounded img-detail" src="{{ animal.foto.url }}">
			{% else %}
				<img class="img-fluid  rounded img-detail" src="/media/m1000x1000.jpeg">
			{% endif %}
		</div>
		<div class="col-md-9">
			<div class="row">
				<button onclick="location.href='{% url 'card' id=animal.id %}'" class='m-3 forms-btn btn btn-primary' type='submit'>Карточка питомца</button>
				<button onclick="location.href='{% url 'history' id=animal.id %}'" class='m-3 forms-btn btn btn-primary' type='submit'>История заболеваний</button>
				<button onclick="location.href='{% url 'change_animal' id=animal.id %}'" class='m-3 forms-btn btn btn-warning' type='submit'>Редактировать</button>
				<button type="button" class="m-3 forms-btn btn btn-danger" data-toggle="modal" data-target="#exampleModal">Выписаться</button>
			</div>
			<table class="table table-hover">
			  <thead>
			  </thead>
			  <tbody>
			    <tr>
			      <td>{% if animal.nickname %} {{ animal.nickname }} {% else %} Кличка питомца {% endif%}</td>
			    </tr>
	
			    <tr>
			    	<td>{% if animal.animal %} {{ animal.animal }} {% else %} Питомец {% endif%}</td>
			    </tr>
			    <tr>
			    	<td>{% if animal.breed %} {{ animal.breed }} {% else %} Порода {% endif%}</td>
			    </tr>
			    <tr>
			      <td>{% if animal.age %} {{ animal.age }} полных лет {% else %} Кол-во полных лет {% endif%}</td>
			    </tr>

			  </tbody>
			</table>
		</div>
	</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Вы точно хотите удалить питомца?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<button onclick="location.href='{% url 'delete_animal' id=animal.id %}'" class='m-3 forms-btn btn btn-danger' type='submit'>Да</button>	
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

personal/templates/personal/change.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
	Редактироать профиль
{% endblock %}

{% block content_title %}
	<p class="m">Редактироать профиль</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <a href="{% url 'personal' %}">Личный кабинет</a> / <span>Редактироать профиль</span></p>
{% endblock %}

{% block content %}
	<div class="col-md-8 offset-md-2">
		<form method="POST" action="{% url 'change' %}" enctype="multipart/form-data">
			{% csrf_token %}

			{% for item in form %}
			<div class="forms">
				<p class="forms-name">{{ item.label }}</p>
				{{ item }}
			</div>
			{% endfor %}




			<button class='forms-btn btn btn-secondary' type='submit'>Изменить</button>
		</form>

		{# Assumes you setup the password_reset view in your URLconf #}
		<!-- <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p> -->
	</div>

{% endblock %}

personal/templates/personal/change_staff.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
	Редактироать профиль
{% endblock %}

{% block content_title %}
	<p class="m">Редактироать профиль</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <a href="{% url 'personal' %}">Личный кабинет</a> / <span>Редактироать профиль</span></p>
{% endblock %}

{% block content %}
	<div class="col-md-8 offset-md-2">
		<form method="POST" action="{% url 'change_staff' %}" enctype="multipart/form-data">
			{% csrf_token %}

			{% for item in form %}
			<div class="forms">
				<p class="forms-name">{{ item.label }}</p>
				{{ item }}
			</div>
			{% endfor %}




			<button class='forms-btn btn btn-secondary' type='submit'>Изменить</button>
		</form>

		{# Assumes you setup the password_reset view in your URLconf #}
		<!-- <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p> -->
	</div>

{% endblock %}

personal/templates/personal/changeanimal.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block title %}
	Редактировать
{% endblock %}


{% block content_title %}
	<p class="m">Редактировать</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <a href="{% url 'personal' %}">Личный кабинет</a> / <a href="{% url 'get_animal' id=idan %}">Страничка питомца</a> / <span>Редактировать</span></p>
{% endblock %}

{% block content %}
	<div class="col-md-8 offset-md-2">
		<form method="POST" id="personForm" action="{% url 'change_animal' id=idan %}" enctype="multipart/form-data" data-breeds-url="{% url 'ajax_load_breeds' %}">
			{% csrf_token %}

			{% for item in form %}
			<div class="forms">
				<p class="forms-name">{{ item.label }}</p>
				{{ item }}
			</div>
			{% endfor %}

			<button class='forms-btn btn btn-secondary' type='submit'>Изменить</button>
		</form>

		{# Assumes you setup the password_reset view in your URLconf #}
		<!-- <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p> -->
	</div>
	
  <script>

	$("#id_animal").change(function () {
	  var url = $("#personForm").attr("data-breeds-url");  // get the url of the `load_cities` view
	  var animalId = $(this).val();  // get the selected country ID from the HTML input

	  $.ajax({                       // initialize an AJAX request
	    url: '{% url 'ajax_load_breeds' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
	    data: {
	      'animal': animalId      // add the country id to the GET parameters
	    },
	    success: function (data) {   // `data` is the return of the `load_cities` view function
	      $("#id_breed").html(data);  // replace the contents of the city input with the data that came from the server
	    }
	  });

	});
  </script>
{% endblock %}

personal/templates/personal/city_dropdown_list_options.html
<option value="">---------</option>
{% for breed in breeds %}
	<option value="{{ breed.pk }}">{{ breed.name }}</option>
{% endfor %}

personal/templates/personal/personal.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}



{% block title %}
	Личный кабинет
{% endblock %}

{% block content_title %}
	<p class="m">Личный кабинет</p>
	<p class="s"><a href="{% url 'index' %}">Главная</a> / <span>Личный кабинет</span></p>
{% endblock %}

{% block content %}
	<div class="row docdetail">
		<div class="col-md-3 d-flex justify-content-center align-items-center">
			{% if user.foto %}
				<img class="img-fluid  rounded img-detail" src="{{ user.foto.url }}">
			{% else %}
				<img class="img-fluid  rounded img-detail" src="/media/user.jpg">
			{% endif %}
		</div>
		<div class="col-md-9">
			<div class="row">
				{% if user.is_staff %}
				<button onclick="location.href='{% url 'clients' %}'" class='m-3 forms-btn btn btn-success' type='submit'>Мои клиенты</button>
				<button onclick="location.href='{% url 'change_staff' %}'" class='m-3 forms-btn btn btn-warning' type='submit'>Редактировать профиль</button>
				{% else %}
				<button onclick="location.href='{% url 'add_animal' %}'" class='m-3 forms-btn btn btn-primary' type='submit'>Добавить питомца</button>
				<button onclick="location.href='{% url 'change' %}'" class='m-3 forms-btn btn btn-warning' type='submit'>Редактировать профиль</button>
				{% endif %}
				<button type="button" class="m-3 forms-btn btn btn-danger" data-toggle="modal" data-target="#exampleModal">Выйти</button>
			</div>
			<table class="table table-hover">
			  <thead>
			  </thead>
			  <tbody>
			    <tr>
			      <td>{% if user.username %} {{ user.username }} {% else %} Логин {% endif%}</td>
			    </tr>
			    <tr>
			      <td>{% if user.first_name %} {{ user.first_name }} {% else %} Имя {% endif%}</td>
			    </tr>
			    <tr>
			    	<td>{% if user.last_name %} {{ user.last_name }} {% else %} Фамилия {% endif%}</td>
			    </tr>
			    <tr>
			    	<td>{% if user.middle_name %} {{ user.middle_name }} {% else %} Отчество {% endif%}</td>
			    </tr>
			    <tr>
			      <td>{% if user.email %} {{ user.email }} {% else %} Email {% endif%}</td>
			    </tr>
			    <tr>
			      <td>С нами с {{ user.date_joined }}</td>
			    </tr>
			  </tbody>
			</table>
		</div>
	</div>
		<div class="docdetail">
			
			{% if user.is_staff %} 
				<p><b>Образование:</b> {{ pers.education }}</p>
				<p><b>Квалификация:</b> {{ pers.qualification }}</p>
				<p><b>Оценка:</b> {{ pers.points }}</p>
				<p><b>Общая информация:</b> {{ pers.description }}</p>
			{% else %}
			<table class="table table-hover">
			  <thead>
			  </thead>
			  <tbody>
			    <tr>
			    	<td><b>Район</b></td>
			      <td>{% if pers.district %} {{ pers.district }} {% else %} Не выбран {% endif%}</td>
			    </tr>
			    </tbody>
			</table>
			{% endif %}
		</div>
		{% if animals %}
		<div class="docdetail m-2">
			<p><b>Мои питомцы</b></p>
		</div>
		<div class="row">
			{% for animal in animals %}
				<div class="col-md-4 col-6 doc-box" onclick="location.href='{% url 'get_animal' id=animal.id  %}';">
					<div class="doc-img">
						<img class="img-fluid" src="{% if animal.foto %} {{ animal.foto.url }} {% else %} /media/m1000x1000.jpeg {%endif%}">
					</div>
					<p class="f">{{ animal.nickname }}</p> 
					<p class="s">{{ item.position }}</p>
				</div>
			{% endfor %}
		</div>
		{% endif %}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Вы точно хотите выйти?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<button onclick="location.href='{% url 'logout' %}'" class='m-3 forms-btn btn btn-danger' type='submit'>Да</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}